version: "3"

networks:
  xsolla-test-infrastructure-network:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: xsolla-test-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PWD}
      MYSQL_USER: ${DB_USER}
    networks:
      - xsolla-test-infrastructure-network
  backend:
    container_name: xsolla-test-backend
    build:
      context: ../
      dockerfile: Dockerfile
    image: xsolla/xsolla-test
    restart: on-failure
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - xsolla-test-infrastructure-network
    ports:
      - "8080:8080"